# Generated by Django 5.0.7 on 2024-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='colour',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
